# Spring Application Name
spring.application.name=SpotTrack Platform

# Default to development when no explicit profile is provided.
spring.profiles.default=${SPRING_PROFILES_ACTIVE:dev}

# Shared Spring DataSource Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Shared Spring Data JPA Hibernate Configuration
spring.jpa.hibernate.naming.physical-strategy=com.spottrack.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Application Information for Documentation

# Elements take their values from maven pom.xml build-related information
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# JWT Configuration Properties
authorization.jwt.secret=spottrack-secret-key-for-jwt-signing-that-is-long-enough-to-satisfy-the-hs512-algorithm-requirement-of-512-bits-minimum
authorization.jwt.expiration.days=7

# i18n message bundles
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Flyway Configuration
spring.flyway.enabled=false


# Stripe keys
## Dev key
stripe.api-key=${STRIPE_API_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}
stripe.success-url=${STRIPE_SUCCESS_URL:http://localhost:4200/payment/success}
stripe.cancel-url=${STRIPE_CANCEL_URL:http://localhost:4200/payment/cancel}
