@US28 @analytics
Feature: Downtime financial impact calculator
  As a business owner
  I want to quantify the estimated monetary loss for each hour a machine is out of service
  So that I understand the real impact of breakdowns

  Scenario: Estimated loss of a broken equipment
    Given a key equipment of the gym is out of service
    When the administrator opens the financial impact of the equipment
    Then the system returns an estimated loss amount based on historical demand

  Scenario: Monthly inefficiency report
    Given the monthly operating period of the gym has ended
    When the business owner reviews the general maintenance balance
    Then the system returns the total hidden cost generated by equipment downtime
